### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by Samarth-G** [MatthewFuchs/Ogopogo-Tech#10]
Develop a use case diagram to illustrate the interactions between system actors and the functionalities provided by the software. This diagram will visually represent the various use cases or scenarios in which users interact with the system to achieve specific goals.

**Comment by lilyy1** [comment]
The diagram has been added to the repository before the creation of the issue. The additional text has been completed however, it is not added to the repository as the TAs would like a pdf submitted for M2.
