### ISSUE TITLE
Update profile page

### ISSUE THREAD

**Issue by MatthewFuchs** [MatthewFuchs/Ogopogo-Tech#75]
Update the profile page to include everything stored in the database, as well as remove things that shouldn't be included. First name, last name, birthdate, email, password and optional profile picture. Also may be a good idea to include a description if it can be included in the database.

**Comment by lilyy1** [comment]
Just wanted to let you know, i completed the update profile page already as i needed it to finish off the completed update user details functionality.

**Comment by MatthewFuchs** [comment]
Completed by Lily earlier
